### ISSUE TITLE
v3接口在Spring Boot Jar包模式下无法读取证书

### ISSUE THREAD

**Issue by 19940727** [Javen205/IJPay#49]
### 版本信息
- IJPay 版本: 2.7.5
- 开发环境: Linux
- 支付方式: 微信支付
- 
### 报错信息 （注意格式化）

```
IJPayHttpResponse response = WxPayApi.v3(
                    RequestMethod.POST,
                    WxDomain.CHINA.toString(),
                    WxApiType.JS_API_PAY.toString(),
                    wechatPaymentPlatform.getMchId(),
                    getSerialNumber(wechatPaymentPlatform),
                    null,
                    wechatPaymentPlatform.getApiClientKeyPath(),
                    JSONUtil.toJsonStr(unifiedOrderModel)

cn.hutool.core.io.IORuntimeException: File not exist: /home/web/payment/target/payment-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/config/v3-dev/apiclient_key.pem
	at cn.hutool.core.io.file.FileReader.checkFile(FileReader.java:300)
	at cn.hutool.core.io.file.FileReader.<init>(FileReader.java:57)
	at cn.hutool.core.io.file.FileReader.create(FileReader.java:37)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1872)
	at cn.hutool.core.io.FileUtil.readString(FileUtil.java:1896)
	at cn.hutool.core.io.FileUtil.readUtf8String(FileUtil.java:1848)
	at com.ijpay.core.kit.PayKit.getPrivateKey(PayKit.java:413)
	at com.ijpay.core.kit.PayKit.createSign(PayKit.java:352)
	at com.ijpay.core.kit.WxPayKit.buildAuthorization(WxPayKit.java:444)
	at com.ijpay.wxpay.WxPayApi.v3(WxPayApi.java:253)
	at com.ijpay.wxpay.WxPayApi.v3(WxPayApi.java:337)


```

### 问题描述（包括回显步骤、截图 ）

Spring Boot Jar包部署在Linux时无法正常读取证书，IDEA开发情况下是正常的。

### 预期效果描述 

Linux也应该可以读取到证书。

### 交流群

- IJPay 让支付触手可及交流群：723992875
- TNWX 微信系开发脚手架交流群：114196246

**Comment by Javen205** [comment]
参考 https://github.com/Javen205/IJPay/issues/37
